version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: weekly
          time: "11:00"
          timezone: EST
      open-pull-requests-limit: 99
      assignees:
          - RDIL
    - package-ecosystem: npm
      directory: "/cherry/"
      schedule:
          interval: weekly
          time: "11:00"
          timezone: EST
      open-pull-requests-limit: 10
      assignees:
          - RDIL
