make_preview_task:
  auto_cancellation: true
  env:
    JEKYLL_ENV: production
  bundler_cache:
    folder: /usr/local/bundle
    fingerprint_script: |
      ruby -v
      cat Gemfile
    populate_script: gem update && bundle install
  build_and_test_script: jekyll build
  cleanup_before_upload_script: rm -rf _site/static
  site_build_artifacts:
    path: _site/**/**
  container:
    image: ruby:latest
