container:
    image: node:14

Build_task:
    env:
        NODE_ENV: production
    Yarn_cache:
        folder: node_modules
        reupload_on_changes: true
    Dependencies_script: yarn
    Build_script: yarn build
    Site_Preview_artifacts:
        path: build/**/**
