Build_task:
    auto_cancellation: true
    env:
        NODE_ENV: production
    build_script: yarn build
    site_preview_artifacts:
        path: build/**/**
    container:
        image: node:latest
