Build_task:
    env:
        NODE_ENV: production
    yarn_cache:
        folder: .yarn/cache
    cherry_yarn_cache:
        folder: cherry/.yarn/cache
    prepopulate_script: yarn
    build_script: yarn build
    site_preview_artifacts:
        path: build/**/**
    container:
        image: node:latest
