container:
    image: node:16

Build_task:
    env:
        NODE_ENV: production
    Yarn_cache:
        folder: .yarn/cache
        reupload_on_changes: true
    Root_Next_cache:
        folder: root/build
        reupload_on_changes: true
    Dependencies_script: yarn
    Build_script: yarn build
