[build]
command = "yarn install && yarn build"
publish = "build/"

[[headers]]
for = "/*"

[[headers.values]]
Referrer-Policy = "same-origin"

[[redirects]]
from = "/update"
to = "https://github.com/hyperiumjailbreak/client/releases"
status = 301
force = true

[[redirects]]
from = "https://www.rdil.rocks/"
to = "https://rdil.rocks"
status = 301
force = true

[[redirects]]
from = "https://cirrusbuilder.rdil.rocks/*"
to = "https://rdil.rocks/cirrus-builder"
status = 301
force = true

[[redirects]]
from = "/peacock"
to = "https://discord.gg/suPq4BewQm"
status = 301
force = true

[[plugins]]
package = "netlify-plugin-cache-nextjs"
[plugins.inputs]
build_dir_path = "root"

[[plugins]]
package = "/.yarn/netlify-cache"
[plugins.inputs]
paths = ["docs/node_modules/.cache"]
