[build]
command = "yarn install && yarn build"
publish = "build/"

[[headers]]
for = "/*"

[headers.values]
Referrer-Policy = "same-origin"
Cache-Control = "max-age: 43200"

[[redirects]]
from = "https://www.rdil.rocks/"
to = "https://rdil.rocks"
status = 301
force = true

[[redirects]]
from = "https://cirrusbuilder.rdil.rocks/*"
to = "https://rdil.rocks/cirrus-builder"
status = 301
force = true
